import 'package:tutorai/shared/widgets/plant_card.dart';

List plantCards = [
  PlantCard(
    imagePath: "tomato.png",
    regionName: "Kumluca Cam",
    plantName: "Domates",
    temperatureValue: "23",
    highTemperatureValue: "25",
    lowTemperatureValue: "3",
    highTemperatureValueClock: "12:25",
    lowTemperatureValueClock: "03:51",
    humidityValue: "50",
    highHumidityValue: "68",
    lowHumidityValue: "21",
    highHumidityValueClock: "12:25",
    lowHumidityValueClock: "03:51",
  ),
  PlantCard(
    imagePath: "strawberry.png",
    regionName: "Aydın Dağ",
    plantName: "Çilek",
    temperatureValue: "23",
    highTemperatureValue: "25",
    lowTemperatureValue: "3",
    highTemperatureValueClock: "12:25",
    lowTemperatureValueClock: "03:51",
    humidityValue: "50",
    highHumidityValue: "68",
    lowHumidityValue: "21",
    highHumidityValueClock: "12:25",
    lowHumidityValueClock: "03:51",
  ),
  PlantCard(
    imagePath: "tomato.png",
    regionName: "Kumluca Cam",
    plantName: "Domates",
    temperatureValue: "23",
    highTemperatureValue: "25",
    lowTemperatureValue: "3",
    highTemperatureValueClock: "12:25",
    lowTemperatureValueClock: "03:51",
    humidityValue: "50",
    highHumidityValue: "68",
    lowHumidityValue: "21",
    highHumidityValueClock: "12:25",
    lowHumidityValueClock: "03:51",
  ),
  PlantCard(
    imagePath: "strawberry.png",
    regionName: "Aydın Dağ",
    plantName: "Çilek",
    temperatureValue: "23",
    highTemperatureValue: "25",
    lowTemperatureValue: "3",
    highTemperatureValueClock: "12:25",
    lowTemperatureValueClock: "03:51",
    humidityValue: "50",
    highHumidityValue: "68",
    lowHumidityValue: "21",
    highHumidityValueClock: "12:25",
    lowHumidityValueClock: "03:51",
  ),
  PlantCard(
    imagePath: "tomato.png",
    regionName: "Kumluca Cam",
    plantName: "Domates",
    temperatureValue: "23",
    highTemperatureValue: "25",
    lowTemperatureValue: "3",
    highTemperatureValueClock: "12:25",
    lowTemperatureValueClock: "03:51",
    humidityValue: "50",
    highHumidityValue: "68",
    lowHumidityValue: "21",
    highHumidityValueClock: "12:25",
    lowHumidityValueClock: "03:51",
  ),
  PlantCard(
    imagePath: "strawberry.png",
    regionName: "Aydın Dağ",
    plantName: "Çilek",
    temperatureValue: "23",
    highTemperatureValue: "25",
    lowTemperatureValue: "3",
    highTemperatureValueClock: "12:25",
    lowTemperatureValueClock: "03:51",
    humidityValue: "50",
    highHumidityValue: "68",
    lowHumidityValue: "21",
    highHumidityValueClock: "12:25",
    lowHumidityValueClock: "03:51",
  ),
];
